name: Feature Test 2GP
on:
    push:
        branches:
            - feature/**
jobs:
    feature-test:
        name: "Feature Test 2GP"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/metecho-demo/d2x:latest
            options: --user root
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GHCR_TOKEN }}
            env:
                DEV_HUB_AUTH_URL: "${{ secrets.DEV_HUB_AUTH_URL }}"
                CUMULUSCI_SERVICE_github: "{ \"username\": \"${{ github.actor }}\", \"token\": \"${{ secrets.GITHUB_TOKEN }}\", \"email\": \"${{ secrets.GH_EMAIL }}\" }"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh
            - name: Set dev org as default org
              run: cci org default dev
            - name: Build Feature Test Package
              run: cci flow run build_feature_test_package --org dev | tee cumulusci-flow.log
              shell: bash
            - name: Set Commit Status
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
              run: |
                  VERSION=$(cat cumulusci-flow.log | grep -o "04t[a-zA-Z0-9]*")
                  gh api \
                    --method POST \
                    -H "Accept: application/vnd.github.v3+json" \
                    '/repos/${{ github.repository }}/statuses/${{ github.sha }}' \
                    -f state='success' \
                    -f description="version_id: $VERSION" \
                    -f context='Build Feature Test Package'
              shell: bash
            - name: Run Feature Test
              run: cci flow run ci_feature_2gp
            - name: Delete Scratch Org
              if: ${{ always() }}
              run: |
                cci org scratch_delete dev
              shell: bash